name = "l2c-proxy"
main = "src/index.ts"
compatibility_date = "2024-04-01"
workers_dev = true
preview_urls = true

[[durable_objects.bindings]]
name = "TUNNELS"
class_name = "Tunnel"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Tunnel"]

[vars]
AUTH_TOKEN = ""
